# Site settings
title: Lineage Mapper - Robust Cell Tracking System for Live Cell Image Analysis
email: michael.majurski@nist.gov
description: > # this means to ignore newlines until "baseurl:"
 An open source, highly accurate, overlap-based cell tracking system that tracks live cells across a set of time-lapse images.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: none
github_username:  mmajurski

# Build settings
markdown: kramdown
